CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY AUTO_INCREMENT,
	USER_NAME VARCHAR(255) NOT NULL UNIQUE,
	USER_EMAIL VARCHAR(255) NOT NULL UNIQUE,
	USER_PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE DATA(
	USER_ID INT NOT NULL,
	FILE_NAME VARCHAR(255) NOT NULL,
	FILE_CREATION DATE,
	PRIMARY KEY(USER_ID, FILE_NAME)
);

INSERT INTO USERS(USER_NAME, USER_EMAIL, USER_PASSWORD)
	VALUES ('Nico', 'test@test.com', 'password');

INSERT INTO USERS(USER_NAME, USER_EMAIL, USER_PASSWORD)
	VALUES ('Saul', 'test2@test.com', 'password');

INSERT INTO USERS(USER_NAME, USER_EMAIL, USER_PASSWORD)
	VALUES ('Abraham', 'test3@test.com', 'password');

-- INSERT INTO USERS(USER_ID, USER_NAME, USER_EMAIL, USER_PASSWORD)
	-- VALUES(1, 'Nico', 'prueba@prueba.com', 'password');
	
-- SELECT * FROM USERS;