CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY,
	USER_NAME VARCHAR(255) NOT NULL,
	USER_EMAIL VARCHAR(255) NOT NULL,
	USER_PASSWORD VARCHAR(255) NOT NULL
)

CREATE TABLE DATA(
	USER_ID INT NOT NULL,
	FILE_NAME VARCHAR(255) NOT NULL,
	FILE_CREATION DATE,
	PRIMARY KEY(USER_ID, FILE_NAME)
)

-- INSERT INTO USERS(USER_ID, USER_NAME, USER_EMAIL, USER_PASSWORD)
	-- VALUES(1, 'Nico', 'prueba@prueba.com', 'password');
	
-- SELECT * FROM USERS;