CREATE TABLE USERS(
	USER_ID INT AUTO_INCREMENT,
	USER_NAME VARCHAR(255) NOT NULL UNIQUE,
	USER_EMAIL VARCHAR(255) NOT NULL UNIQUE,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	PRIMARY KEY(USER_ID)
);

CREATE TABLE FILE(
	FILE_ID INT AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	FILE_NAME VARCHAR(255) NOT NULL,
	FILE_CREATION DATE NOT NULL,
	FILE_PATH VARCHAR(255) NOT NULL,
	PRIMARY KEY (FILE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);